In [1]:
import numpy as np

In [3]:
lis = [1,2,3,4,5,6]

In [5]:
arr = np.array(lis)

In [7]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
arr2d = np.array(my_mat)

In [17]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(1)

array([1.])

In [31]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

In [33]:
np.linspace(0,200,50)

array([  0.        ,   4.08163265,   8.16326531,  12.24489796,
        16.32653061,  20.40816327,  24.48979592,  28.57142857,
        32.65306122,  36.73469388,  40.81632653,  44.89795918,
        48.97959184,  53.06122449,  57.14285714,  61.2244898 ,
        65.30612245,  69.3877551 ,  73.46938776,  77.55102041,
        81.63265306,  85.71428571,  89.79591837,  93.87755102,
        97.95918367, 102.04081633, 106.12244898, 110.20408163,
       114.28571429, 118.36734694, 122.44897959, 126.53061224,
       130.6122449 , 134.69387755, 138.7755102 , 142.85714286,
       146.93877551, 151.02040816, 155.10204082, 159.18367347,
       163.26530612, 167.34693878, 171.42857143, 175.51020408,
       179.59183673, 183.67346939, 187.75510204, 191.83673469,
       195.91836735, 200.        ])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.random.rand(5)

array([0.94814622, 0.84419259, 0.43515304, 0.79057848, 0.12983167])

In [41]:
np.random.randn(3)

array([ 2.15495985, -1.03690058, -0.05346913])

In [43]:
np.random.randint(1,80,5)

array([50,  8, 15, 49, 16])

In [45]:
my_arr=np.arange(0,24)

In [51]:
my_arr.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
my_arr.max()

23

In [55]:
my_arr.min()

0

In [57]:
my_arr.argmax()

23

In [61]:
arr = np.arange(0,11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[3]

3

In [67]:
arr[3:7]

array([3, 4, 5, 6])

In [69]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [71]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[0:4]=25

In [75]:
arr

array([25, 25, 25, 25,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr1=arr

In [79]:
arr1

array([25, 25, 25, 25,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr1[6:10]=44

In [83]:
arr1

array([25, 25, 25, 25,  4,  5, 44, 44, 44, 44, 10])

In [85]:
arr

array([25, 25, 25, 25,  4,  5, 44, 44, 44, 44, 10])

In [87]:
arr_copy=arr1.copy()

In [91]:
arr_copy

array([25, 25, 25, 25,  4,  5, 44, 44, 44, 44, 10])

In [93]:
arr_copy[0:7]=76

In [95]:
arr

array([25, 25, 25, 25,  4,  5, 44, 44, 44, 44, 10])

In [97]:
arr1

array([25, 25, 25, 25,  4,  5, 44, 44, 44, 44, 10])

In [99]:
arr_copy

array([76, 76, 76, 76, 76, 76, 76, 44, 44, 44, 10])

In [103]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [105]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [111]:
arr_2d[1][1]

25

In [113]:
arr_2d[2,1]

40

In [115]:
arr_2d[2,2]

45

In [125]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [127]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [130]:
arr=np.arange(0,11)


In [132]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [136]:
bool_array=arr > 5

In [138]:
bool_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [140]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [142]:
arr[arr<6]

array([0, 1, 2, 3, 4, 5])

In [144]:
arr = np.arange(0,11)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [150]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [152]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [154]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [156]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [158]:
1/0

ZeroDivisionError: division by zero

In [160]:
arr/arr

/tmp/ipykernel_1650/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [162]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [164]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [166]:
np.log(arr)


/tmp/ipykernel_1650/2931416741.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])